require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/enigma'
require './lib/key'
require './lib/offset'
require './lib/encrypt'
require './lib/decrypt'
require './lib/shift'
